apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
data:
  DB_HOST: 'postgres-service'
---
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQ=
